version: "3"

services:
  postgres:
    image: postgres:13.2
    command: postgres -N 2000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - local
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.2
    command: sh -c "redis-server --requirepass password"
    networks:
      - local
    ports:
      - 6379:6379

  rabbitmq:
    # Use Bitnami (legacy namespace) image with delayed exchange plugin available
    image: bitnamilegacy/rabbitmq:3.12
    # Ensure we pull/run an image compatible with x86_64 hosts
    platform: linux/amd64
    environment:
      # Match app configuration (config.rabbitHttpUrl derives from these)
      - RABBITMQ_USERNAME=indexer
      - RABBITMQ_PASSWORD=supersecret
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      # Download community plugin (.ez) for delayed exchange and enable it
      # (the URL must match the RabbitMQ minor version)
      - RABBITMQ_COMMUNITY_PLUGINS=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez
      # Enable required plugins: management UI + delayed exchange
      - RABBITMQ_PLUGINS=rabbitmq_management rabbitmq_delayed_message_exchange
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - local

  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    profiles: ["manual"]
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - local
    ports:
      - 9200:9200

networks:
  local:
    driver: bridge
